// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewDatabaseProject.Models;

#nullable disable

namespace NewDatabaseProject.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20251202191525_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ClassModelsMemberModel", b =>
                {
                    b.Property<string>("membersemail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classesname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classesdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classestime")
                        .HasColumnType("TEXT");

                    b.HasKey("membersemail", "Classesname", "Classesdate", "Classestime");

                    b.HasIndex("Classesname", "Classesdate", "Classestime");

                    b.ToTable("ClassModelsMemberModel");
                });

            modelBuilder.Entity("ClassModelsTrainerModel", b =>
                {
                    b.Property<string>("traineremployee_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classes_Teachingname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classes_Teachingdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classes_Teachingtime")
                        .HasColumnType("TEXT");

                    b.HasKey("traineremployee_id", "Classes_Teachingname", "Classes_Teachingdate", "Classes_Teachingtime");

                    b.HasIndex("Classes_Teachingname", "Classes_Teachingdate", "Classes_Teachingtime");

                    b.ToTable("ClassModelsTrainerModel");
                });

            modelBuilder.Entity("NewDatabaseProject.Models.ClassModels", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("time")
                        .HasColumnType("TEXT");

                    b.Property<string>("minimum_membership_access")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("name", "date", "time");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("NewDatabaseProject.Models.MemberModel", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("birthday")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date_signed_up")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("membership_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("email");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("NewDatabaseProject.Models.MembershipTypeModel", b =>
                {
                    b.Property<string>("Access_Level")
                        .HasColumnType("TEXT");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Access_Level");

                    b.ToTable("MembershipTypes");
                });

            modelBuilder.Entity("NewDatabaseProject.Models.TrainerModel", b =>
                {
                    b.Property<string>("employee_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("birthday")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date_started_working")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("membership_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("employee_id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("ClassModelsMemberModel", b =>
                {
                    b.HasOne("NewDatabaseProject.Models.MemberModel", null)
                        .WithMany()
                        .HasForeignKey("membersemail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewDatabaseProject.Models.ClassModels", null)
                        .WithMany()
                        .HasForeignKey("Classesname", "Classesdate", "Classestime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassModelsTrainerModel", b =>
                {
                    b.HasOne("NewDatabaseProject.Models.TrainerModel", null)
                        .WithMany()
                        .HasForeignKey("traineremployee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewDatabaseProject.Models.ClassModels", null)
                        .WithMany()
                        .HasForeignKey("Classes_Teachingname", "Classes_Teachingdate", "Classes_Teachingtime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
